#!/usr/bin/env sh

DEST=${1:?provide installer path}
INSTALLER_NAME=qt-opensource-linux-x64-5.3.0.run
INSTALLER_UNPACK_DIR=$(pwd)/InstallerPackage
FRAGMENT=gcc_

printf "Installing qt at: ${INSTALLER_UNPACK_DIR}\n"

wget http://download.qt-project.org/official_releases/qt/5.3/5.3.0/${INSTALLER_NAME}
chmod +x ${INSTALLER_NAME}
./"${INSTALLER_NAME}" --dump-binary-data -o "${INSTALLER_UNPACK_DIR}"

(
    mkdir "${DEST}"
    cd "${DEST}"
    for file in "${INSTALLER_UNPACK_DIR}"/qt.*.${FRAGMENT}*/*7z ; do
        7zr x $file | grep -v ^Extract
    done
)
for d in "${DEST}"/*/${FRAGMENT}*/bin/
do
    printf '[Paths]\nPrefix=..\n' > $d/qt.conf
done
